// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNl_aca2hVpegWhop0CQPToIHc43F-kM',
    appId: '1:150341222003:web:a4726017515e7955e73406',
    messagingSenderId: '150341222003',
    projectId: 'zippy-user',
    authDomain: 'zippy-user.firebaseapp.com',
    storageBucket: 'zippy-user.appspot.com',
    measurementId: 'G-74TTVYD2FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDApV9V-1PQ2sE4XDcD3TDAemKuYcHx1bI',
    appId: '1:150341222003:android:ff365ddaca64a81ce73406',
    messagingSenderId: '150341222003',
    projectId: 'zippy-user',
    storageBucket: 'zippy-user.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9K3YM6QIWSnuIAg6ykQKRcoSAsDxvm3s',
    appId: '1:150341222003:ios:e5aca6cc6f9f8c02e73406',
    messagingSenderId: '150341222003',
    projectId: 'zippy-user',
    storageBucket: 'zippy-user.appspot.com',
    iosBundleId: 'com.ziipy.user.zippyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9K3YM6QIWSnuIAg6ykQKRcoSAsDxvm3s',
    appId: '1:150341222003:ios:9a8b5b2d2d2c9767e73406',
    messagingSenderId: '150341222003',
    projectId: 'zippy-user',
    storageBucket: 'zippy-user.appspot.com',
    iosBundleId: 'com.ziipy.user.zippyUser.RunnerTests',
  );
}
